# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dual/cs5170417/Desktop/Lab-6/Lab-6.cache/wt [current_project]
set_property parent.project_path /home/dual/cs5170417/Desktop/Lab-6/Lab-6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dual/cs5170417/Desktop/Lab-6/Lab-6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/dual/cs5170417/Desktop/Lab-5/array_sum_bin.coe
add_files -quiet /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/ip/dist_mem_gen_1_1/dist_mem_gen_1.dcp
set_property used_in_implementation false [get_files /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/ip/dist_mem_gen_1_1/dist_mem_gen_1.dcp]
read_vhdl -library xil_defaultlib {
  /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/new/CPU.vhd
  /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/new/debounce.vhd
  /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/new/display_interface.vhd
  /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/new/freq_divider.vhd
  /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/new/Main.vhd
}
read_ip -quiet /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/constrs_1/imports/Lab-6 initial/lab8usb.xdc}}
set_property used_in_implementation false [get_files {{/home/dual/cs5170417/Desktop/Lab-6/Lab-6.srcs/constrs_1/imports/Lab-6 initial/lab8usb.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
